### ISSUE TITLE
Use of JobQueueGroup::singleton was deprecated in MediaWiki 1.37.

### ISSUE THREAD

**Issue by Ascor8522** [Kenny2github/RecentChangesWebhooks#3]
Title says it all.

## Log ##

```log
PHP Deprecated:
Use of JobQueueGroup::singleton was deprecated in MediaWiki 1.37.
[Called from RecentChangesWebhooksHooks::onChange
in %EXTENSIONS_HOME%/RecentChangesWebhooks/RecentChangesWebhooks.class.php at line 29]
in %WIKI_HOME%/includes/debug/MWDebug.php on line 381
```

## Version ##

Running MediaWiki version 1.39

**Comment by jacob-g** [comment]
Looks like this just needs to use the dependency injection system, see https://github.com/InternationalScratchWiki/scratch-confirmaccount-v3/blob/master/src/SpecialConfirmAccounts.php#L42 for how we did it for CA3.
